/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simp;

import java.sql.Connection;

import lombok.extern.slf4j.Slf4j;
import simp.gui.Gui;

@Slf4j
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App instance = new App();
        log.info("Hello: {}", System.getProperty("user.dir"));
        System.out.println(instance.getGreeting());
        Gui gui = new Gui();
        // Connection connection = Db.getConnection();

    }

}
